system(['python ' python_script ...
                 ' -r 1' ...
                 ' -rstc 0007' ... %reset all but fsm
                 ' -f 1' ...
                 ' -ff ' flashfile ...
                 ' -get 1' ...
                 ' -ds ' num2str(datasize) ...
                 ' -o ' outfile ...
                 ' -ep00 ' num2str(hex2dec('10130')) ... %[enable_FSM enable_datapath dont_reset] [MSB LSB] [0150]
                 ' -ep02 ' num2str(framelength) ...
                 ' -clkdiv ' num2str(clkdiv) ... % 
                 ' -rpp 1' ... % reprogram of PLL
                 ' -c0d ' num2str(spadduty*1000) ... 
                 ' -c0p ' num2str(spadphase*1000) ...
                 ' -ns ' num2str(numsnaps)]);